{{- if .Values.monitoring.enabled }}
{{- if .Values.monitoring.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "agentgateway.fullname" . }}-proxy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "agentgateway.labels" . | nindent 4 }}
    {{- with .Values.monitoring.serviceMonitor.extraLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.monitoring.proxy.selectorName }}
  endpoints:
  - port: metrics
    path: /metrics
    interval: {{ .Values.monitoring.serviceMonitor.interval }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "agentgateway.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "agentgateway.labels" . | nindent 4 }}
    {{- with .Values.monitoring.serviceMonitor.extraLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "agentgateway.name" . }}
  endpoints:
  - port: metrics
    path: /metrics
    interval: {{ .Values.monitoring.serviceMonitor.interval }}
{{- end }}
{{- if .Values.monitoring.grafanaDashboard.enabled }}
{{- if .Values.monitoring.serviceMonitor.enabled }}
---
{{- end }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "agentgateway.fullname" . }}-dashboard
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "agentgateway.labels" . | nindent 4 }}
    {{ .Values.monitoring.grafanaDashboard.label.key }}: {{ .Values.monitoring.grafanaDashboard.label.value | quote }}
data:
  agentgateway.json: |
{{ .Files.Get "files/agentgateway-dashboard.json" | indent 4 }}
{{- end }}
{{- end }}
