# yaml-language-server: $schema=https://agentgateway.dev/schema/config
config:
  tracing:
    otlpEndpoint: http://localhost:4317
    randomSampling: true
binds:
- port: 3000
  listeners:
  - protocol: HTTP
    routes:
    - policies:
        localRateLimit:
        - type: requests
          limit: 50
          unit: seconds
      backends:
      - host: localhost:8080
